routes/web.php
<?php

use Illuminate\Support\Facades\Route;
Route::get('/admin/login', 'Admin\AuthController@loginPage')->name('admin.login');

Route::post('loginAdmin', 'Admin\AuthController@login');

Route::group(['prefix' => 'admin', 'middleware' => ['admin'], 'namespace' => 'Admin'], function () {

    Route::get('/dashboard', 'HomeController@index')->name('admin.dashboard');

    Route::get('logout', 'AuthController@logout')->name('logout');
    Route::resource('task', 'TaskController');
    Route::resource('user', 'UserController');
    Route::post('updateTaskStatus', 'TaskController@updateStatus')->name('updateTaskStatus');

});
Route::get('/{path}', 'Web\HomeController@index')->where('path', '.*');

resources/views/admin/partials/errors.blade.php
@if(!empty(session('patch_error')))
<div class="alert alert-danger">
        <li>{{ session('patch_error') }}.</li>
</div>
@elseif(count($errors)>0)
    <div class="alert alert-danger">
        @foreach($errors->all() as $error)
            <li>{{ $error }}.</li>
        @endforeach
    </div>
@endif

resources/views/admin/partials/footer.blade.php
<footer class="main-footer">
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->

resources/views/admin/partials/head.blade.php
<meta charset="utf-8">


<meta http-equiv="X-UA-Compatible" content="IE=edge">


<title>Schedule Admin panel

</title>


<link rel="stylesheet" href="{{asset('AdminLTE/plugins/fontawesome-free/css/all.min.css')}}">

<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

<link rel="stylesheet"
      href="{{asset('AdminLTE/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css')}}">

<link rel="stylesheet" href="{{asset('AdminLTE/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">

<link rel="stylesheet" href="{{asset('AdminLTE/plugins/jqvmap/jqvmap.min.css')}}">
<link rel="stylesheet" href="{{asset('AdminLTE/dist/css/adminlte.min.css')}}">
<link rel="stylesheet" href="{{asset('AdminLTE/plugins/overlayScrollbars/css/OverlayScrollbars.min.css')}}">

<link rel="stylesheet" href="{{asset('AdminLTE/plugins/daterangepicker/daterangepicker.css')}}">

<link rel="stylesheet" href="{{asset('AdminLTE/plugins/summernote/summernote-bs4.css')}}">

<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

resources/views/admin/partials/header.blade.php
<!-- Navbar -->


<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

</nav>


<!-- /.navbar -->





<!-- Main Sidebar Container -->


<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{route('admin.dashboard')}}" class="brand-link">
        <div class="name__user">
            <img src="{{asset('AdminLTE/dist/img/userimg.png')}}" alt="">
            <span class="brand-text font-weight-light"> Hi {{auth()->user()->name}}</span>
        </div>
        <!--name__user-->
    </a>



    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->



        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item"><a href="{{route('task.index')}}" class="nav-link">
                        <p>
                            Tasks
                        </p>
                    </a>

                </li>
                <li class="nav-item"><a href="{{route('user.index')}}" class="nav-link">
                        <p>
                            Users
                        </p>
                    </a>

                </li>
                <li class="nav-item">
                    <a id='logout' href="{{route('logout')}}" class="nav-link">
                        <p><i class="fa fa-sign-out" aria-hidden="true"></i>Log Out</p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

resources/views/admin/partials/scripts.blade.php
<script src="{{asset('AdminLTE/plugins/jquery/jquery.min.js')}}"></script>
<script src="{{asset('AdminLTE/plugins/jquery-ui/jquery-ui.min.js')}}"></script>
<script>
  $.widget.bridge('uibutton', $.ui.button)


</script>
<script src="{{asset('AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<script src="{{asset('AdminLTE/plugins/chart.js/Chart.min.js')}}"></script>
<script src="{{asset('AdminLTE/plugins/sparklines/sparkline.js')}}"></script>
<script src="{{asset('AdminLTE/plugins/jqvmap/jquery.vmap.min.js')}}"></script>
<script src="{{asset('AdminLTE/plugins/jqvmap/maps/jquery.vmap.usa.js')}}"></script>
<script src="{{asset('AdminLTE/plugins/jquery-knob/jquery.knob.min.js')}}"></script>
<script src="{{asset('AdminLTE/plugins/moment/moment.min.js')}}"></script>
<script src="{{asset('AdminLTE/plugins/daterangepicker/daterangepicker.js')}}"></script>
<script src="{{asset('AdminLTE/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js')}}"></script>
<script src="{{asset('AdminLTE/plugins/summernote/summernote-bs4.min.js')}}"></script>
<script src="{{asset('AdminLTE/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('AdminLTE/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('AdminLTE/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{asset('AdminLTE/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
<script src="{{asset('AdminLTE/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js')}}"></script>
<script src="{{asset('AdminLTE/dist/js/adminlte.js')}}"></script>
<script src="{{asset('AdminLTE/dist/js/pages/dashboard.js')}}"></script>
<script src="{{asset('AdminLTE/plugins/bootstrap/js/bootstrap-select.min.js')}}"></script>
<script src="{{asset('AdminLTE/plugins/select2/js/select2.full.min.js')}}"></script>
<script src="https://js.pusher.com/7.0/pusher.min.js"></script>